"""Render ChromHA theme profiles into a Home Assistant theme file."""

from __future__ import annotations

from .const import (
    DAYNIGHT_OFF,
    ICON_AUTO_URL_BASE,
    DAYNIGHT_SUN,
    DAYNIGHT_THEME,
    ICON_SET_NONE,
    ICON_URL_BASE,
    MODE_AUTO,
    MODE_DARK,
    MODE_SUN,
    STYLE_GLASS,
    WEATHER_ICON_MAP,
    icon_map,
)
from .palette import Palette, build_palette, mix

HEADER = """\
# ===========================================================================
#  GENERATED BY THE CHROMA INTEGRATION - DO NOT EDIT
#
#  This file is rewritten whenever a ChromHA entity changes. Any manual edit
#  will be lost. Change the entities instead.
#
#  Weather icons bundled from github.com/Makin-Things/weather-icons (MIT),
#  based on the amCharts free animated weather icons (CC BY 4.0).
#  Palette approach inspired by the Caule Themes Pack by Ricardo Correia.
# ===========================================================================
"""


def _glass_background(pal: Palette) -> str:
    """A generated gradient backdrop, so no image files are needed."""
    tint = mix(pal.background, pal.accent, 0.35)
    tint2 = mix(pal.background, pal.accent_soft, 0.22)
    return (
        f"radial-gradient(at 18% 12%, {tint} 0px, transparent 55%), "
        f"radial-gradient(at 82% 88%, {tint2} 0px, transparent 50%), "
        f"{pal.background}"
    )


def _card_background(pal: Palette, style: str, opacity: int) -> str:
    if style != STYLE_GLASS:
        return pal.surface
    r, g, b = (int(pal.surface_raised[i : i + 2], 16) for i in (1, 3, 5))
    return f"rgba({r}, {g}, {b}, {opacity / 100:.2f})"


def _icon_lines(icon_set: str, night: bool, follow_sun: bool) -> list[str]:
    if icon_set == ICON_SET_NONE:
        return []

    if follow_sun:
        # Point at the sun-aware endpoint. The URLs never change, so the theme
        # file does not need rewriting at sunrise or sunset.
        lines = ["# Weather icons (resolved per request from sun.sun)"]
        for condition in WEATHER_ICON_MAP:
            lines.append(
                f'weather-icon-{condition}: '
                f'url("{ICON_AUTO_URL_BASE}/{condition}.svg")'
            )
        return lines

    lines = [f"# Weather icons ({'night' if night else 'day'})"]
    for condition, filename in icon_map(night).items():
        lines.append(
            f'weather-icon-{condition}: url("{ICON_URL_BASE}/{filename}.svg")'
        )
    return lines


def _use_night_icons(options: dict, *, dark: bool) -> bool:
    """Decide whether this variant gets night artwork.

    Follow theme keys off the variant being rendered, which costs nothing
    because both variants already ship in the same file. Follow sun keys off
    the live sun state, which is accurate but needs a rebuild at sunrise and
    sunset.
    """
    from .const import CONF_ICON_DAYNIGHT, DEFAULTS

    choice = options.get(CONF_ICON_DAYNIGHT, DEFAULTS[CONF_ICON_DAYNIGHT])
    if choice == DAYNIGHT_OFF:
        return False
    if choice == DAYNIGHT_SUN:
        return bool(options.get("is_night", False))
    if choice == DAYNIGHT_THEME:
        return dark
    return False


def render_variant(options: dict, *, dark: bool) -> list[str]:
    """Render one light or dark variant as a list of unindented lines."""
    from .const import (
        CONF_CONTRAST,
        CONF_ICON_SET,
        CONF_OPACITY,
        CONF_RADIUS,
        CONF_STYLE,
        DEFAULTS,
    )

    accent = options["resolved_accent"]
    style = options.get(CONF_STYLE, DEFAULTS[CONF_STYLE])
    radius = options.get(CONF_RADIUS, DEFAULTS[CONF_RADIUS])
    opacity = options.get(CONF_OPACITY, DEFAULTS[CONF_OPACITY])
    icon_set = options.get(CONF_ICON_SET, DEFAULTS[CONF_ICON_SET])
    boost = options.get(CONF_CONTRAST, DEFAULTS[CONF_CONTRAST])

    pal = build_palette(accent, dark=dark, contrast_boost=boost)
    card = _card_background(pal, style, opacity)
    glass = style == STYLE_GLASS

    lines: list[str] = [
        "# Core",
        f'primary-color: "{pal.accent}"',
        f'light-primary-color: "{pal.accent_soft}"',
        f'dark-primary-color: "{pal.accent_strong}"',
        "accent-color: var(--light-primary-color)",
        "graph-color: var(--primary-color)",
        f'primary-background-color: "{pal.background}"',
        "secondary-background-color: var(--primary-background-color)",
        f'divider-color: "{pal.divider}"',
        f'disabled-color: "{pal.disabled}"',
        "",
        "# Text",
        f'primary-text-color: "{pal.text}"',
        f'secondary-text-color: "{pal.text_muted}"',
        "text-primary-color: var(--primary-text-color)",
        "disabled-text-color: var(--disabled-color)",
        "text-on-state-color: var(--ha-card-background)",
        f'link-text-color: "{pal.icon_active}"',
        "",
        "# Surfaces",
        f'ha-card-background: "{card}"' if not glass else f"ha-card-background: {card}",
        "card-background-color: var(--primary-background-color)",
        f"ha-card-border-radius: {radius}px",
        "ha-card-border-color: var(--divider-color)",
        f"ha-card-border-width: {'1px' if glass else '0px'}",
        "ha-card-box-shadow: none",
        "material-background-color: var(--primary-background-color)",
        "material-secondary-background-color: var(--ha-card-background)",
        "",
        "# Icons and states",
        f'state-icon-color: "{pal.icon}"',
        f'state-icon-active-color: "{pal.icon_active}"',
        f'state-active-color: "{pal.icon_active}"',
        f'state-inactive-color: "{pal.icon}"',
        "state-icon-unavailable-color: var(--disabled-color)",
        "",
        "# Sidebar and header",
        "sidebar-icon-color: var(--secondary-text-color)",
        "sidebar-text-color: var(--primary-text-color)",
        "sidebar-background-color: var(--primary-background-color)",
        "sidebar-selected-icon-color: var(--primary-color)",
        "sidebar-selected-text-color: var(--primary-color)",
        "app-header-background-color: var(--primary-background-color)",
        "app-header-text-color: var(--primary-text-color)",
        "app-header-edit-background-color: var(--ha-card-background)",
        "",
        "# Controls",
        "control-slider-color: var(--primary-color)",
        "control-slider-background: var(--disabled-color)",
        "control-slider-background-opacity: 0.2",
        "slider-color: var(--primary-color)",
        "slider-track-color: var(--disabled-color)",
        "switch-checked-color: var(--primary-color)",
        "switch-checked-button-color: var(--primary-color)",
        "switch-checked-track-color: var(--light-primary-color)",
        "switch-unchecked-button-color: var(--disabled-color)",
        "switch-unchecked-color: var(--divider-color)",
        "switch-unchecked-track-color: var(--divider-color)",
        "",
        "# Forms",
        "ha-color-form-background: var(--ha-card-background)",
        "ha-color-form-background-hover: var(--divider-color)",
        "ha-color-form-background-disabled: var(--primary-background-color)",
        "input-fill-color: var(--ha-card-background)",
        "input-ink-color: var(--primary-text-color)",
        "input-label-ink-color: var(--secondary-text-color)",
        "input-idle-line-color: var(--divider-color)",
        "input-hover-line-color: var(--primary-color)",
        "input-dropdown-icon-color: var(--secondary-text-color)",
        "input-disabled-fill-color: var(--primary-background-color)",
        "input-disabled-ink-color: var(--disabled-text-color)",
        "input-disabled-label-ink-color: var(--disabled-text-color)",
        "mdc-text-field-fill-color: var(--ha-card-background)",
        "mdc-text-field-ink-color: var(--primary-text-color)",
        "mdc-text-field-label-ink-color: var(--secondary-text-color)",
        "mdc-select-fill-color: var(--ha-card-background)",
        "mdc-select-ink-color: var(--primary-text-color)",
        "mdc-select-label-ink-color: var(--secondary-text-color)",
        "mdc-select-idle-line-color: var(--divider-color)",
        "mdc-select-hover-line-color: var(--primary-color)",
        "mdc-select-dropdown-icon-color: var(--secondary-text-color)",
        "code-editor-background-color: var(--secondary-background-color)",
        "markdown-code-background-color: var(--divider-color)",
        "",
        "# Tables",
        "table-row-background-color: var(--primary-background-color)",
        "table-row-alternative-background-color: var(--ha-card-background)",
    ]

    if glass:
        lines += [
            "",
            "# Glass",
            f"lovelace-background: '{_glass_background(pal)}'",
        ]

    from .const import CONF_ICON_DAYNIGHT

    follow_sun = options.get(
        CONF_ICON_DAYNIGHT, DEFAULTS[CONF_ICON_DAYNIGHT]
    ) == DAYNIGHT_SUN
    icons = _icon_lines(icon_set, _use_night_icons(options, dark=dark), follow_sun)
    if icons:
        lines += [""] + icons

    return lines


def _indent(lines: list[str], spaces: int) -> list[str]:
    pad = " " * spaces
    return [(pad + ln) if ln.strip() else "" for ln in lines]


def render_profile(name: str, options: dict) -> list[str]:
    """Render one named theme block."""
    from .const import CONF_MODE, DEFAULTS

    mode = options.get(CONF_MODE, DEFAULTS[CONF_MODE])
    out = [f"{name}:"]

    if mode == MODE_SUN:
        # One variant only. Which one depends on where the sun is, so this
        # profile is rewritten at sunrise and sunset.
        out += _indent(
            render_variant(options, dark=bool(options.get("is_night", False))), 2
        )
        out.append("")
        return out

    if mode == MODE_AUTO:
        out.append("  modes:")
        out.append("    light:")
        out += _indent(render_variant(options, dark=False), 6)
        out.append("    dark:")
        out += _indent(render_variant(options, dark=True), 6)
    else:
        out += _indent(render_variant(options, dark=mode == MODE_DARK), 2)

    out.append("")
    return out


def render_file(profiles: dict[str, dict]) -> str:
    """Render every profile into one theme file."""
    out = [HEADER]
    for name in sorted(profiles):
        out += render_profile(name, profiles[name])
    return "\n".join(out) + "\n"
